### ISSUE TITLE
complied xcframwork throws "missing required module 'internal'"

### ISSUE THREAD

**Issue by atkhalsa** [sindresorhus/ExceptionCatcher#4]
I have my own framework and that is now dependent on ExceptionCatcher.

After compiling my framework to xcframework and then using into test app, before distribution is throwing error at build time with the message `missing required module "internal"'

Do you know how can I get this `internal` module of exceptionCatcher into the xcframework?

![image](https://user-images.githubusercontent.com/4521592/187525799-de3d8499-3a98-4c5b-a3b8-c75ac0b3c7ee.png)

**Comment by sindresorhus** [comment]
I think this is a limitation of XCFramework: https://forums.swift.org/t/issue-with-third-party-dependencies-inside-a-xcframework-through-spm/41977/8

Can you try out 2.0.1? https://github.com/sindresorhus/ExceptionCatcher/releases/tag/v2.0.1

**Comment by atkhalsa** [comment]
Thank you very much 🙇.  That seems to have fixed it, but I will know more after I resolved issue with other packages I am using
